version: "3.9"

services:
  nginx:
    image: nginx:1.21.5-alpine
    ports:
      - 3002:3001
      # - 441:441
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # 여기서 오타나서 굉장히 삽질함ㅠ
      - ./error.log:/var/log/nginx/error.log
      - ./ssh:/etc/nginx/ssh

    container_name: service-proxy
    # depends_on:
    #   - api

  # api:
  #   container_name: ${APP_NAME}
  #   build:
  #     context: .
  #     args:
  #     - WORKDIR=${WORKDIR}
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - TZ = "Asia/Seoul"
  #     - NODE_ENV=${NODE_ENV}

  #   # entrypoint: ["/bin/bash"]
  #   entrypoint: ["/bin/sh", "-c"]
  #   command:
  #     - |
  #       ${WORKDIR}/entrypoint.sh
  #   tty: true
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"